# Deploy contexts
# Environment variables here override variables set in the web UI.
#
# https://docs.netlify.com/site-deploys/overview/#deploy-contexts
# https://docs.netlify.com/configure-builds/file-based-configuration/#deploy-contexts

[context.deploy-preview.environment]
  HUGO_VERSION = "0.100.2"
  NODE_VERSION = "16"
  CXXFLAGS = "-std=c++17"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.100.2"
  NODE_VERSION = "16"
  CXXFLAGS = "-std=c++17"

[context.production.environment]
  HUGO_VERSION = "0.100.2"
  NODE_VERSION = "16"
  CXXFLAGS = "-std=c++17"

# Redirects
# - Default status is a 301 unless otherwise specified.
# - First match wins: put wildcards AFTER specific paths!
# - Wildcards include empty matches: /v1.0/* WILL match /v1.0
#
# docs: https://docs.netlify.com/routing/redirects/
#
# validator: https://play.netlify.com/redirects

# Make sure we're not redirecting anything under /images

[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200

# Bypass the landing page

[[redirects]]
  from = "/"
  to = "/preview/"
  force = true

# Catch-all for old links to /latest (now called /preview)

[[redirects]]
  from = "/latest/*"
  to = "/preview/:splat"
  force = true

# Redirect old cloud docs to root of current

[[redirects]]
  from = "/:version/yugabyte-cloud/*"
  to = "/preview/yugabyte-cloud/"
  force = true

# Redirect EOL docs to the archive site
# (And note that v1.0-1.2 don't exist)

[[redirects]]
  from = "/v1.0/*"
  to = "https://docs-archive.yugabyte.com/"
  force = true

[[redirects]]
  from = "/v1.1/*"
  to = "https://docs-archive.yugabyte.com/"
  force = true

[[redirects]]
  from = "/v1.2/*"
  to = "https://docs-archive.yugabyte.com/"
  force = true

[[redirects]]
  from = "/v1.3/*"
  to = "https://docs-archive.yugabyte.com/v1.3/"
  force = true

[[redirects]]
  from = "/v2.0/*"
  to = "https://docs-archive.yugabyte.com/v2.0/"
  force = true

[[redirects]]
  from = "/v2.1/*"
  to = "https://docs-archive.yugabyte.com/v2.1/"
  force = true

[[redirects]]
  from = "/v2.2/*"
  to = "https://docs-archive.yugabyte.com/v2.2/"
  force = true

# Redirect older versions of specific sections

[[redirects]]
  from = "/:version/comparisons/*"
  to = "/preview/comparisons/:splat"
  force = true

[[redirects]]
  from = "/:version/contribute/*"
  to = "/preview/contribute/:splat"
  force = true

[[redirects]]
  from = "/:version/faq/*"
  to = "/preview/faq/:splat"
  force = true

[[redirects]]
  from = "/:version/integrations/smart-driver/"
  to = "/preview/integrations/jdbc-driver/"
  force = true

[[redirects]]
  from = "/:version/integrations/*"
  to = "/preview/integrations/"
  force = true

# (this is the old version of integrations)
[[redirects]]
  from = "/:version/develop/ecosystem-integrations/*"
  to = "/preview/integrations/"
  force = true

[[redirects]]
  from = "/:version/legal/*"
  to = "/preview/legal/:splat"
  force = true

[[redirects]]
  from = "/:version/releases/*"
  to = "/preview/releases/:splat"
  force = true

[[redirects]]
  from = "/:version/troubleshoot/*"
  to = "/preview/troubleshoot/:splat"
  force = true

[[redirects]]
  from = "/:version/yedis/*"
  to = "/preview/yedis/"
  force = true

# Stable quick-starts need defaults,
# since archiving from /preview removes aliases

[[redirects]]
  from = "/stable/quick-start/install/"
  to = "/stable/quick-start/install/macos/"
  force = true

[[redirects]]
  from = "/stable/quick-start/create-local-cluster/"
  to = "/stable/quick-start/create-local-cluster/macos/"
  force = true

[[redirects]]
  from = "/stable/quick-start/explore/"
  to = "/stable/quick-start/explore/ysql/"
  force = true

# Yugabyte Extensions top hit

[[redirects]]
  from = "/preview/api/ysql/extensions/"
  to = "/preview/explore/ysql-language-features/pg-extensions/"
  force = true

# Hugo resource caching plugin configuration
# https://github.com/cdeleeuwe/netlify-plugin-hugo-cache-resources#readme

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"

    [plugins.inputs]
    # If it should show more verbose logs (optional, default = true)
    debug = true
    # Relative path to source directory in case you use Hugo's "--s" option
    srcdir = "docs"

[[headers]]
  #
  # https://docs.netlify.com/configure-builds/file-based-configuration/#headers
  #
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline'; connect-src https://ka-f.fontawesome.com/releases/ https://www.google-analytics.com/ https://stats.g.doubleclick.net/ https://umbcujcbe8-dsn.algolia.net/ https://umbcujcbe8-1.algolianet.com/ https://umbcujcbe8-2.algolianet.com/ https://umbcujcbe8-3.algolianet.com/; script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://maxcdn.bootstrapcdn.com https://cdn.jsdelivr.net https://www.googletagmanager.com/ https://kit.fontawesome.com/ https://www.google-analytics.com/ https://umbcujcbe8-dsn.algolia.net/ https://umbcujcbe8-1.algolianet.com/ https://umbcujcbe8-2.algolianet.com/ https://umbcujcbe8-3.algolianet.com/; style-src 'self' 'unsafe-inline' https://maxcdn.bootstrapcdn.com https://cdnjs.cloudflare.com https://fonts.googleapis.com https://use.fontawesome.com https://docs.yugabyte.com https://ka-f.fontawesome.com/releases/; font-src 'self' https://docs.yugabyte.com/fonts/ https://cdnjs.cloudflare.com/ https://use.fontawesome.com https://fonts.gstatic.com https://ka-f.fontawesome.com/releases/; object-src 'none'; img-src 'self' https://docs.yugabyte.com/images/favicon.ico https://www.google-analytics.com/; child-src 'self' 'unsafe-inline' https://www.youtube.com/"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin"
    Permissions-Policy = "disabled"
    X-XSS-Protection = "1"
